apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-superset
spec:
  selector:
    app: {{ .Release.Name }}-superset
  type: ClusterIP
  ports:
    - name: sshd-svc
      port: 2222
      targetPort: sshd
    - name: vnc-gui-svc
      port: 5900
      targetPort: vnc-gui
  
